### ISSUE TITLE
JavaScript Ice/exception test failure

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#294] opened 2018-11-12 14:09 UTC
With distribution testing on macOS Mojave:
```
[ running client/server with sliced format test - 11/12/18 11:32:24 ]
- Config: ws,Firefox
(/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/cpp/test/Ice/echo/build/macosx/shared/server --Ice.Warn.Connections=1 --Ice.MessageSizeMax=8192 --Ice.PrintAdapterReady=1 --Ice.Default.SlicedFormat=1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Size=1 --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ThreadPool.Server.SizeMax=3 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.SizeWarn=0)
(executing `Ice/exceptions/Server' on `<selenium.webdriver.firefox.webdriver.WebDriver (session="7fe0b968-ef03-b647-a1ad-d4c84f4083db")>' args = ['--Ice.Warn.Connections=1', '--Ice.PrintAdapterReady=1', '--Ice.Default.SlicedFormat=1', '--Ice.ThreadPool.Server.Size=1', '--Ice.Default.Protocol=ws', '--Ice.Default.Host=127.0.0.1', '--Ice.IPv6=0', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0'])
(executing `Ice/exceptions/Client' on `<selenium.webdriver.firefox.webdriver.WebDriver (session="7fe0b968-ef03-b647-a1ad-d4c84f4083db")>' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.Default.Protocol=ws', '--Ice.Default.SlicedFormat=1'])
testing object adapter registration exceptions... ok
testing servant registration exceptions... ok
testing servant locator registration exceptions... ok
testing value factory registration exception... ok
testing stringToProxy... ok
testing checked cast... ok
catching exact types... ok
catching base types... ok
catching derived types... ok
catching unknown user exception... ok
testing memory limit marshal exception...ok
unexpected exception while running test: ::Ice::UnknownLocalException
unknown: "src/Ice/WSTransceiver.cpp:1321: ::Ice::ConnectionLostException:
connection lost: recv() returned zero
0 IceUtil::Exception::Exception(char const*, int) in libIce.37.dylib
1 Ice::LocalException::LocalException(char const*, int) in libIce.37.dylib
2 Ice::ConnectionLostException::ConnectionLostException(char const*, int, int) in libIce.37.dylib
3 IceInternal::WSTransceiver::preRead(IceInternal::Buffer&) in libIce.37.dylib
4 IceInternal::WSTransceiver::read(IceInternal::Buffer&) in libIce.37.dylib
5 Ice::ConnectionI::read(IceInternal::Buffer&) in libIce.37.dylib
6 Ice::ConnectionI::message(IceInternal::ThreadPoolCurrent&) in libIce.37.dylib
7 IceInternal::ThreadPool::run(IceUtil::Handle<IceInternal::ThreadPool::EventHandlerThread> const&) in libIce.37.dylib
8 IceInternal::ThreadPool::EventHandlerThread::run() in libIce.37.dylib
9 startHook(void*) in libIce.37.dylib
10 _pthread_body in libsystem_pthread.dylib
11 _pthread_start in libsystem_pthread.dylib
12 thread_start in libsystem_pthread.dylib
"
```

**Comment by pepone** [comment] 2018-11-19 21:07
I push a fix to increase the retries in f6686cc8e94601e62c9893e78e456d40f51ff4ac

I was not able to reproduce the issue but I think is due to the connection lost cause by the memory limit exception, and the exception server not reconnecting on time

see https://github.com/zeroc-ice/ice/blob/f6686cc8e94601e62c9893e78e456d40f51ff4ac/js/test/Ice/exceptions/ServerAMD.js#L35-L37

let's wait to see if that get fixed in next build

**Closed** 2018-11-20 16:46 UTC
Labels: js, testsuite
