### ISSUE TITLE
IceGrid assertion with IceGrid/replication test

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2103] opened 2024-05-02 14:38 UTC
```
 	ucrtbased.dll!00007ffde05bae2d()	Unknown
 	ucrtbased.dll!00007ffde05c0c6f()	Unknown
 	ucrtbased.dll!00007ffde05bebc8()	Unknown
 	ucrtbased.dll!00007ffde05c18af()	Unknown
>	icegridregistry.exe!IceGrid::SessionServantManager::deactivate(const std::string & __formal) Line 90	C++
 	ice38a0d.dll!IceInternal::ServantManager::destroy() Line 448	C++
 	ice38a0d.dll!Ice::ObjectAdapterI::destroy() Line 345	C++
 	ice38a0d.dll!IceInternal::ObjectAdapterFactory::destroy::__l2::<lambda_1>::operator()(const std::shared_ptr<Ice::ObjectAdapterI> & adapter) Line 94	C++
 	ice38a0d.dll!std::for_each<std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<Ice::ObjectAdapterI>>>>,`IceInternal::ObjectAdapterFactory::destroy'::`2'::<lambda_1>>(std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<Ice::ObjectAdapterI>>>> _First, std::_List_iterator<std::_List_val<std::_List_simple_types<std::shared_ptr<Ice::ObjectAdapterI>>>> _Last, IceInternal::ObjectAdapterFactory::destroy::__l2::<lambda_1> _Func) Line 285	C++
 	ice38a0d.dll!IceInternal::ObjectAdapterFactory::destroy() Line 96	C++
 	ice38a0d.dll!IceInternal::Instance::destroy() Line 1660	C++
 	ice38a0d.dll!Ice::Communicator::destroy() Line 39	C++
 	ice38a0d.dll!Ice::Service::run(int argc, const char * const * argv, const Ice::InitializationData & initData, int version) Line 814	C++
 	ice38a0d.dll!Ice::Service::main(int argc, const char * const * argv, const Ice::InitializationData & initializationData, int version) Line 660	C++
 	ice38a0d.dll!Ice::Service::main(const std::vector<std::string,std::allocator<std::string>> & args, const Ice::InitializationData & initData, int version) Line 675	C++
 	ice38a0d.dll!Ice::Service::main(int argc, const wchar_t * const * argv, const Ice::InitializationData & initializationData, int version) Line 667	C++
 	icegridregistry.exe!wmain(int argc, wchar_t * * argv) Line 235	C++
 	icegridregistry.exe!invoke_main() Line 91	C++
 	icegridregistry.exe!__scrt_common_main_seh() Line 288	C++
 	icegridregistry.exe!__scrt_common_main() Line 331	C++
 	icegridregistry.exe!wmainCRTStartup(void * __formal) Line 17	C++
 	kernel32.dll!00007ffe29ce7344()	Unknown
 	ntdll.dll!00007ffe2a9226b1()	Unknown
```

**Comment by bernardnormier** [comment] 2024-11-04 15:07
Could be a duplicate of #2426.

**Closed** 2024-11-04 15:08 UTC
Labels: bug
