### ISSUE TITLE
csharp Ice/metrics test failure with .netcore

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#217] opened 2018-09-26 09:04 UTC
```*** [31/56] Running csharp/Ice/metrics tests ***
[ running client/server test - 09/26/18 03:07:18 ]
- Config: amd64,tcp
(dotnet /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/msbuild/server/netstandard2.0/netcoreapp2.1/server.dll --Ice.Warn.Connections=1 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Protocol=1 --Ice.ThreadPool.Server.Size=1 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ThreadPool.Server.SizeMax=3 --Ice.Trace.Retry=1 --Test.BasePort=14000 --Ice.LogFile=/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/server-092618-0307.log --Ice.ThreadPool.Server.SizeWarn=0)
(dotnet /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/msbuild/client/netstandard2.0/netcoreapp2.1/client.dll --Ice.Warn.Connections=1 --Ice.Trace.Network=2 --Ice.Trace.Protocol=1 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.Trace.Retry=1 --Test.BasePort=14000 --Ice.LogFile=/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/client-092618-0307.log)
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing connection metrics... ok
testing connection establishment metrics... ok
testing endpoint lookup metrics... ok
testing dispatch metrics... ok
testing invocation metrics... System.Exception: Exception of type 'System.Exception' was thrown.
at Test.AllTests.test(Boolean b) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/TestCommon/TestHelper.cs:line 182
at AllTests.allTests(TestHelper helper, CommunicatorObserverI obsv) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/AllTests.cs:line 1080
at Client.run(String[] args) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/Client.cs:line 36
at Test.TestDriver.runTest[T](String[] args) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/TestCommon/TestHelper.cs:line 195
saved /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/client-092618-0307.log
saved /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-g++-default/csharp/test/Ice/metrics/server-092618-0307.log
test in Ice/metrics failed:
Traceback (most recent call last):
File "../scripts/Util.py", line 1567, in run
self.runWithDriver(current)
File "../scripts/Util.py", line 1596, in runWithDriver
current.driver.runClientServerTestCase(current)
File "../scripts/LocalDriver.py", line 564, in runClientServerTestCase
self.runner.runClientSide(client, current, host)
File "../scripts/LocalDriver.py", line 202, in runClientSide
testcase._runClientSide(current, host)
File "../scripts/Util.py", line 1544, in _runClientSide
self.runClientSide(current)
File "../scripts/Util.py", line 1440, in runClientSide
self._runClient(current, client)
File "../scripts/Util.py", line 1556, in _runClient
client.run(current)
File "../scripts/Util.py", line 1089, in run
process.waitSuccess(exitstatus=exitstatus, timeout=30)
File "../scripts/Expect.py", line 640, in waitSuccess
test(self.exitstatus, exitstatus)
File "../scripts/Expect.py", line 625, in test
raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment] 2018-09-26 09:05
we saw that failure with ` ubuntu bionic64` test VMs

**Comment by bentoi** [comment] 2018-11-12 14:07
Loos like a similar failure occurs with Java on mojave with Java11 dist testing:
```
[ running collocated test - 11/12/18 11:27:01 ]
(/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java -ea -Dtest.class=test.Ice.metrics.Collocated test.TestDriver --Ice.Warn.Connections=1 --Ice.Trace.Network=2 --Ice.Trace.Protocol=1 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.Trace.Retry=1 --Test.BasePort=14100 --Ice.LogFile=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-java@11/java/test/src/main/java/test/Ice/metrics/collocated-111218-1127.log env={'CLASSPATH': '/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-java@11/java/lib/test.jar'})
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing dispatch metrics... ok
testing invocation metrics... java.lang.RuntimeException
at test.Ice.metrics.AllTests.test(AllTests.java:27)
at test.Ice.metrics.AllTests.allTests(AllTests.java:1195)
at test.Ice.metrics.Collocated.run(Collocated.java:50)
at test.TestDriver.main(TestDriver.java:22)
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-java@11/java/test/src/main/java/test/Ice/metrics/collocated-111218-1127.log
```

**Comment by pepone** [comment] 2018-11-19 20:55
Happen on Windows with Java 11 too
```
(C:\Program Files\Java\jdk-11.0.1\bin\java -ea -Dtest.class=test.Ice.metrics.Collocated test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14300 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice-3.7\builds\ice-v140-java@11\java\test\src\main\java\test\Ice\metrics\collocated-111918-1302.log env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice-3.7\\builds\\ice-v140-java@11\\java\\lib\\test.jar'})
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing dispatch metrics... ok
testing invocation metrics... java.lang.RuntimeException
at test.Ice.metrics.AllTests.test(AllTests.java:27)
at test.Ice.metrics.AllTests.allTests(AllTests.java:1195)
at test.Ice.metrics.Collocated.run(Collocated.java:50)
at test.TestDriver.main(TestDriver.java:22)
```

**Comment by bentoi** [comment] 2018-12-13 16:47
I committed a fix for Java, for C# I can't reproduce so I'm closing, let's re-open if it shows up again.

**Comment by pepone** [comment] 2019-07-12 22:48
We get this again in rhel8 VM running C# tests

```
testing endpoint lookup metrics... ok
testing dispatch metrics... ok
testing invocation metrics... current: 0 total: 3 failures: 3 retry: 3 remotes: 5
System.Exception: Exception of type 'System.Exception' was thrown.
at Test.AllTests.test(Boolean b) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/TestCommon/TestHelper.cs:line 167
at AllTests.allTests(TestHelper helper, CommunicatorObserverI obsv) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/Ice/metrics/AllTests.cs:line 1081
at Client.run(String[] args) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/Ice/metrics/Client.cs:line 31
at Test.TestDriver.runTest[T](String[] args) in /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/TestCommon/TestHelper.cs:line 180
saved /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/Ice/metrics/client-071219-2030.log
saved /home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/csharp/test/Ice/metrics/server-071219-2030.log
```

**Closed** 2019-07-16 15:32 UTC
Labels: bug, csharp

**Comment by bentoi** [comment] 2019-07-16 15:35
I think I've nailed it down this time... the test was grouping remote invocations by the connection's "localPort". On Linux, .NET Core sometime reallocated a localPort for an Ice connection used for retrying an invocation. The test expected retries to be performed on Ice connection with distinct localPort.
