### ISSUE TITLE
Should we remove most of these properties from JS, and not add new ones?

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2326] opened 2024-06-20 12:20 UTC
Should we remove most of these properties from JS, and not add new ones?

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2320#discussion_r1646545267_

**Comment by bernardnormier** [comment] 2024-06-20 14:45
A related question is: do we want to allow (or keep allowing) sharing configuration files between Ice applications written in different languages?

If the answer is yes, then it makes sense for Ice-JS to accept but ignore various properties that are not relevant to JS.

If the answer is no, then Ice-JS should only accept properties that are relevant to Ice-JS, and reject all other properties. 
And furthermore, we should remove "config sharing" support like:
https://doc.zeroc.com/ice/3.7/property-reference/ice-plugin#id-.Ice.Plugin.*v3.7-Ice.Plugin.name.cpp
(fortunately I believe it's limited to this Ice.Plugin property)

**Comment by bernardnormier** [comment] 2024-09-23 21:06
Duplicate of #2746.

**Closed by bernardnormier** 2024-09-23 21:06 UTC
Labels: js, cleanup
