### ISSUE TITLE
Escape sequences in doc comments

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1606] opened 2023-12-19 10:53 UTC
```
// Slice
const string ss3 = "\\\\U\\u\\"; /* \\U\u\  */
const string ss4 = "\\\u0041\\"; /* \A\     */
const string ss5 = "\\u0041\\";  /* \u0041\ */
```

This results in invalid Java-generated code, I didn't check other mappings.
```
java-compat/test/build/generated-src/test/Ice/operations/AMD/Test/ss3.java:19: error: illegal unicode escape
2023-12-19T10:37:11.1730511Z  * \\U\u\
2023-12-19T10:37:11.1732024Z         ^
```

Should Slice do as Java and reject `\u` in this case?

**Comment by InsertCreativityHere** [comment] 2023-12-19 16:16
We already reject these in string literals:
```
/* Matches a universal character code that isn't the correct size, or uses incorrect characters. */
<STRING_LITERAL>"\\u"{hex}{0,3}[g-zG-Z]* ... report an error
```

But I'm not sure we should bother checking doc comments. Right now the parser performs no inspection of comments, we just read a raw string and forward it along for the most part. I suspect there's lots of ways to generate bad code through putting weird things in doc comments.

If multiple languages fail to handle to `\u`, then maybe we should start performing comment validation, but if it's just 
Java, or one other language, I wouldn't.

**Comment by InsertCreativityHere** [comment] 2024-11-27 15:50
I don't know how it took me this long, but everything _finally_ clicks!

Think about it, why is a normal comment even making it into the Java generated code?
And why does it look so... screwed up?

This issue is _actually_ a manifestation of https://github.com/zeroc-ice/ice/issues/3192!
The bug where the Slice scanner was treating _all_ C-style comments as doc-comments!

----

I opened  to restore these comments (so all the Slice files are the same across languages),
and indeed, now that #3192 has been fixed, there are no more errors.

**Comment by InsertCreativityHere** [comment] 2024-11-27 19:03
I'm closing this issue as "completed" because the problem is now resolved.
Users are free to put whatever they want in non-doc-comments, and it will never trigger invalid code to be generated,

Note that it may still be possible to put bogus stuff in a doc-comment, but that's a separate issue to tackle IMO.

**Closed by InsertCreativityHere** 2024-11-27 19:03 UTC
Labels: question
