### ISSUE TITLE
javascript import error

### ISSUE THREAD

**Issue by flzxsqcysyhljt** [zeroc-ice/ice#1036] opened 2020-09-11 01:57 UTC
code:
`import request from '@/utils/request'
import { Ice } from 'ice' //3.7.4

const communicator = Ice.initialize();
const proxy = communicator.stringToProxy("user.query.identity:tcp -p xxxx-h x.x.x.x");`

error:
TypeError: m.require is not a function ModuleRegistry.js:25
    require ModuleRegistry.js:25
    forEach self-hosted:266
    require ModuleRegistry.js:23
    js Ice.js:7
    js app.js:71019
    Webpack 24

What should I do about it?

**Comment by pepone** [comment] 2020-09-11 09:21
Can you describe what you are trying to do?

**Comment by pepone** [comment] 2020-09-16 13:48
seems like a duplicate of #1039

**Closed by pepone** 2020-09-16 13:48 UTC
Labels: js
